version: "3.9"

services:
  api-postgres:
    image: ghcr.io/hallboard-team/dotnet-v${DOTNET_VERSION:-10.0}:latest
    container_name: ${CONTAINER_NAME:-template}_api_postgres-v${POSTGRES_VERSION:-17}-dev

    user: "0:0"
    working_dir: /workspaces/app

    volumes:
      - ../:/workspaces/app:Z
      - ~/.cache/vscode-server-shared:/home/vscode/.vscode-server-shared:Z

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      VSCODE_SERVER_DIR: /home/vscode/.vscode-server-shared

      ConnectionStrings__Default: >
        Host=db;Port=5432;
        Database=${DB_NAME:-template_backend_db};
        Username=${DB_USER:-template_backend_user};
        Password=${DB_PASSWORD:-template_backend_password};
        Include Error Detail=true

    ports:
      - "${API_PORT:-5000}:5000"

    depends_on:
      db:
        condition: service_healthy

    command: >
      bash -c "
        dotnet --info &&
        sleep infinity
      "

  db:
    image: docker.io/library/postgres:${POSTGRES_VERSION:-17}-alpine
    container_name: ${CONTAINER_NAME:-template}-backend_db

    environment:
      POSTGRES_USER: ${DB_USER:-template_backend_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-template_backend_password}
      POSTGRES_DB: ${DB_NAME:-template_backend_db}

    ports:
      - "${DB_HOST_PORT:-5433}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data:Z

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-template_backend_user} -d ${DB_NAME:-template_backend_db}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
